### ISSUE TITLE
Sign out

### ISSUE THREAD

**Issue by kennyphan100** [JamesPartsafas/ConcordiaCurriculumManager#10]
As a faculty member, I want to sign out of the CCM website, so I can exit the system.

[Story Points: 1]
[Priority: High]
[Risk: Low]

Tasks:

Demo steps:
Given I’m a logged-in user
When I click on the Sign out button located on the top
Then the system logs me off

**Comment by Dinferno-lol** [comment]
https://github.com/JamesPartsafas/ConcordiaCurriculumManager/assets/77465567/1cd170e2-852d-4c20-8139-c46fdf439a5a
