### ISSUE TITLE
Create a program change dossier

### ISSUE THREAD

**Issue by kennyphan100** [JamesPartsafas/ConcordiaCurriculumManager#11]
As an initiator, I want to create a program change dossier, so I can update the school’s curriculum to industry standards.

[Story Points: 8]
[Priority: High]
[Risk: Medium]

Tasks:

Demo steps:
Given I’m an initiator and I’m on the Edit Program page
When I make the necessary changes and click confirm
Then a confirmation message is displayed, and the system creates a program change dossier

**Comment by JamesPartsafas** [comment]
Duplicate of #6
