### ISSUE TITLE
Choose the approval pipeline

### ISSUE THREAD

**Issue by kennyphan100** [JamesPartsafas/ConcordiaCurriculumManager#13]
As an initiator, I want to choose the approval pipeline, so I can contact the required approvals of relevant parties.

[Story Points: 8]
[Priority: High]
[Risk: Medium]

Tasks:
- [x] #195 
- [x] #253 
- [x] #263 
- [x] #295

Demo steps:
Given I’m an initiator
When I create a dossier for a change
Then a default or custom pipeline can be chosen

**Comment by JamesPartsafas** [comment]
This story is complete as all subtasks have been done.
