### ISSUE TITLE
Add User to Group

### ISSUE THREAD

**Issue by Dinferno-lol** [JamesPartsafas/ConcordiaCurriculumManager#160]
As an admin, I want to add a user to a group.

[Story Points: 2]
[Priority: Medium]
[Risk: Medium]

Demo steps:
Given I'm logged in as an admin,
I can view the manage groups page,
then reach the add user page for a specific group,
and add a user that isn't already in that group.

**Comment by JamesPartsafas** [comment]
This issue is a duplicate of #119

**Comment by Dinferno-lol** [comment]
> This issue is a duplicate of #119

Since the issue you're referencing in question doesn't specify the add or remove user pages specifically I figured this would be required

**Comment by JamesPartsafas** [comment]
> > This issue is a duplicate of #119
> 
> Since the issue you're referencing in question doesn't specify the add or remove user pages specifically I figured this would be required

I just added a line to it to reference adding users.

**Comment by Dinferno-lol** [comment]
https://github.com/JamesPartsafas/ConcordiaCurriculumManager/assets/77465567/37b4d29b-9acb-494f-aad8-4b18225088d0
