### ISSUE TITLE
Approve a dossier

### ISSUE THREAD

**Issue by kennyphan100** [JamesPartsafas/ConcordiaCurriculumManager#17]
As a group member, I want to approve a dossier, so I can forward the dossier to the next party in the approval pipeline.

[Story Points: 8]
[Priority: High]
[Risk: Low]

Tasks:
- [x] #239 

Demo steps:
Given I’m a group member
When I click on a dossier and approve it
Then a confirmation message is displayed and the dossier is sent to the next party to review

**Comment by JamesPartsafas** [comment]
This story is complete as all subtasks have been done.
