### ISSUE TITLE
Receive email notifications for pending approvals

### ISSUE THREAD

**Issue by zihao429** [JamesPartsafas/ConcordiaCurriculumManager#18]
As a group member, I want to receive an email notification of a pending approval dossier, so I can be updated with the new changes.

[Story Points: 8]
[Priority: Low]
[Risk: Medium]

Tasks:
- [x] #308
- [x]  #404

Demo steps:
Given I’m a group member 
When a dossier has been submitted by an initiator in my group
Then an email message will be sent to my email for approval

**Comment by JamesPartsafas** [comment]
All work is complete for this story
