### ISSUE TITLE
Return a dossier

### ISSUE THREAD

**Issue by zihao429** [JamesPartsafas/ConcordiaCurriculumManager#20]
As a group member, I want to return a dossier, so I can send back the dossier to the previous party of the approval pipeline.

[Story Points: 8]
[Priority: High]
[Risk: Low]

Tasks:
- [x] #241 

Demo steps:
Given I’m a group member
When I select a dossier, and click on Return Dossier Button
Then a confirmation message is displayed, and the system will send back the dossier to the previous party of the approval pipeline

**Comment by JamesPartsafas** [comment]
This story is complete as all subtasks have been done.
