### ISSUE TITLE
Assign initiator role

### ISSUE THREAD

**Issue by kennyphan100** [JamesPartsafas/ConcordiaCurriculumManager#22]
As a group master or system administrator, I want to assign initiator role to a faculty member, so I can give faculty members access to initiate a dossier.

[Story Points: 4]
[Priority: Medium]
[Risk: High]

Tasks:

Demo steps:
Given I’m a group master or system administrator
When I click on a faculty member user
Then I should be able to give them the role of initiator

**Comment by JamesPartsafas** [comment]
Pending further changes in requirements, all users who register with the site are considered initiators.
