### ISSUE TITLE
Provide comments to a dossier

### ISSUE THREAD

**Issue by zihao429** [JamesPartsafas/ConcordiaCurriculumManager#23]
As a group member, I want to provide comments to a dossier, so I can provide input to the initiator of the dossier.

[Story Points: 4]
[Priority: Medium]
[Risk: Low]

Tasks:

Demo steps:
Given I’m a group member
When I select a dossier and provide comments, and click on Submit Changes button
Then a confirmation message is displayed, and the system will save the comments to the dossier

**Comment by JamesPartsafas** [comment]
This is a duplicate of #343
