### ISSUE TITLE
Manage access to users

### ISSUE THREAD

**Issue by zihao429** [JamesPartsafas/ConcordiaCurriculumManager#25]
As a system administrator, I want to grant and remove access to users, so I can manage user accounts and their permissions.

[Story Points: 4]
[Priority: Medium]
[Risk: High]

Tasks:

Demo steps:
Given I'm a system administrator, and I'm on the User's page
When I select select a user and click on Add User or Remove User
Then a confirmation message is displayed, and the system will add or remove the user

**Comment by JamesPartsafas** [comment]
This issue is a duplicate of #119
