### ISSUE TITLE
View dossier report

### ISSUE THREAD

**Issue by zihao429** [JamesPartsafas/ConcordiaCurriculumManager#259]
As a user, I want to be able to view the report of a specific dossier, so I can find a summary of the dossier.

[Story Points: 10]
[Priority: Medium]
[Risk: Low]

Tasks:
- [x] #255
- [x] #297
- [x] #435 
- [x] #455 

Demo steps:
Given I’m an initiator and I have submitted a dossier
When I click on Report,
Then the dossier report will be shown

**Comment by zihao429** [comment]
Demo steps:
Given I’m an initiator and I have submitted a dossier
When I click on Report,
Then the dossier report will be shown

**Comment by JamesPartsafas** [comment]
All associated work is complete for this story.
