### ISSUE TITLE
Review a Dossier

### ISSUE THREAD

**Issue by kennyphan100** [JamesPartsafas/ConcordiaCurriculumManager#343]
As a reviewer, I want to be able to review and add a comment to a dossier, so I can request changes to a dossier.

[Story Points: 12]
[Priority: High]
[Risk: Medium]

Tasks:
- [x] https://github.com/JamesPartsafas/ConcordiaCurriculumManager/issues/243
- [x] https://github.com/JamesPartsafas/ConcordiaCurriculumManager/issues/272
 - [x] https://github.com/JamesPartsafas/ConcordiaCurriculumManager/issues/284
 - [x] https://github.com/JamesPartsafas/ConcordiaCurriculumManager/issues/319
 - [x] https://github.com/JamesPartsafas/ConcordiaCurriculumManager/issues/320
- [x] #355 

Demo steps:
Given I’m a reviewer and I am on the "Dossiers Requiring Your Review" page
When I click on the "Review Dossier" icon of a dossier,
Then I can review information about the dossier and I can add a comment.

**Comment by JamesPartsafas** [comment]
All tasks for this story are complete.
