### ISSUE TITLE
Setup front end for add course

### ISSUE THREAD

**Issue by rogersi9** [JamesPartsafas/ConcordiaCurriculumManager#35]
As an initiator, I want to be able to view the UI for adding courses, so that I can input new course information.

This is a subtask of #7 

[Story Points: 5]
[Priority: High]
[Risk: Medium]

**Comment by JamesPartsafas** [comment]
This issue was closed by #121

**Comment by rogersi9** [comment]
[video (1).webm](https://github.com/JamesPartsafas/ConcordiaCurriculumManager/assets/69977233/a997ec53-2f67-4165-9466-3e3be0832785)
