### ISSUE TITLE
Seed engineering curriculums with a web scraper

### ISSUE THREAD

**Issue by fullKTRL** [JamesPartsafas/ConcordiaCurriculumManager#403]
Seed engineering curriculums with a web scraper.

This is a subtask of #357 

[Story Points: 12]
[Priority: Medium]
[Risk: Medium]

Demo steps:
Enter a path for the HTML file to be scraped in the script and run it.
The script should generate a GeneratedCourseGroupings.json.
Add the data to Seeder/src/data/CourseGroupings.json.
Run "npm run validateData".
Should return valid.

**Comment by JamesPartsafas** [comment]
All work has been completed for this story.
