### ISSUE TITLE
Sign-in via CCM

### ISSUE THREAD

**Issue by zihao429** [JamesPartsafas/ConcordiaCurriculumManager#5]
As a non-authenticated user, I want to sign in to the CCM website, so I can initiate, approve, or track a curriculum request through the CCM website.

[Story Points: 4]
[Priority: High]
[Risk: High]

Tasks:
- [x] #3 
- [x] #29 
- [x] #37

Demo steps:
Given I’m a logged-out system user and I’m on the Sign-in page
When I fill in the “Email”, “Password” fields, and I click the Sign-In Button
Then a confirmation message is displayed, and the system signs me in

**Comment by JamesPartsafas** [comment]
This story is complete.

**Comment by Dinferno-lol** [comment]
https://github.com/JamesPartsafas/ConcordiaCurriculumManager/assets/77465567/94c65a36-cce7-474b-b614-80b551d26f45
