### ISSUE TITLE
Reset Password

### ISSUE THREAD

**Issue by zihao429** [JamesPartsafas/ConcordiaCurriculumManager#508]
As a user, I want to be able to reset my password, so that I can access the website even if I forgot my password.

[Story Points: 12]
[Priority: High]
[Risk: High]

Subtasks:
- [x] #509 
- [x] #507 
- [x] #504 
- [x] #503 

Demo steps:
Given I’m a user and go to the curriculum browser,
When I click on "Forgot Password"  and enter an email,
I will receive an email with a link to reset my password.
When I click on that link, I can enter a new password to replace the old one.

**Comment by JamesPartsafas** [comment]
All work has been completed for this story.
