### ISSUE TITLE
Get User Metrics

### ISSUE THREAD

**Issue by Ghaith-Chrit** [JamesPartsafas/ConcordiaCurriculumManager#523]
As an admin, I want to be able to view metrics about how the system is performing and some user-defined metrics 

[Story Points: 12]
[Priority: High]
[Risk: Medium]

Subtasks:
- [x] #524
- [x] #526

Demo steps:
Given I’m an admin and go to the data metrics page
I can view all the available metrics about the system.

**Comment by JamesPartsafas** [comment]
All work has been completed for this story.
