### ISSUE TITLE
Create a course modification request

### ISSUE THREAD

**Issue by zihao429** [JamesPartsafas/ConcordiaCurriculumManager#6]
As an initiator, I want to create a course modification request, so I can update the school’s curriculum to industry standards.

[Story Points: 10]
[Priority: High]
[Risk: Medium]

Tasks:
- [x] #64 
- [x] #91 
- [x] #93
- [x] #123  
- [x] #139  
- [x] #142 
- [x] #143 
- [x] #191  
- [x] #193  
- [x] #205 
- [x] #214 
- [x] #224
- [x] #226
- [x] #286 

Demo steps:
Given I’m an initiator and I’m on the Edit Course page
When I make the changes, and click the Submit Button
Then a confirmation message is displayed, and the system creates a course change dossier

**Comment by JamesPartsafas** [comment]
This story is complete as all subtasks have been done.
