### ISSUE TITLE
Setup endpoints for a course modification request

### ISSUE THREAD

**Issue by kennyphan100** [JamesPartsafas/ConcordiaCurriculumManager#64]
Subtask to set up the backend endpoints for the user story defined at #6 
Create CourseModifyRequest and implement the functions for controller, service, repository, and db context

[Story Points: 2]
[Priority: High]
[Risk: Medium]

**Comment by JamesPartsafas** [comment]
Could you assign story points, risk, priority, etc to this task?

**Comment by zihao429** [comment]
https://drive.google.com/file/d/1fnU_NLWjUszLJ2lQTgB1_A6N001uPFXh/view?usp=drive_link
