### ISSUE TITLE
Create a course creation request

### ISSUE THREAD

**Issue by zihao429** [JamesPartsafas/ConcordiaCurriculumManager#7]
As an initiator, I want to create a course creation request, so I can update the school’s curriculum to industry standards.

[Story Points: 15]
[Priority: High]
[Risk: Medium]

Tasks:
- [x] #27 
- [x] #56 
- [x] #61 
- [x] #66 
- [x] #35 
- [x] #136 
- [x] #140  
- [x] #141 
- [x] #179  

Demo steps:
Given I’m an initiator and I’m on the Add Course page
When I fill in the required fields, and click the Submit Changes Button
Then a confirmation message is displayed, and the system creates an add course dossier

**Comment by JamesPartsafas** [comment]
[createCourse.webm](https://github.com/JamesPartsafas/ConcordiaCurriculumManager/assets/56362880/f0b8fa92-4b88-48bd-a8a9-aa7e8d45260c)
