### ISSUE TITLE
Request to access CCM

### ISSUE THREAD

**Issue by kennyphan100** [JamesPartsafas/ConcordiaCurriculumManager#8]
As a non-authenticated user, I want to create a request to access the Concordia Curriculum Manager (CCM) so I can become an authenticated faculty member.

[Story Points: 4]
[Priority: High]
[Risk: High]

Tasks:
- [X] Create frontend registration page #44 
- [x] #59 

Demo steps:
Given I’m a logged-out system user and I’m on the Registration page
When I fill in the required fields, and I click the Create Acccount Button
Then a confirmation message is displayed that the account is created, and the system signs me in

**Comment by JamesPartsafas** [comment]
This story is complete.

**Comment by JamesPartsafas** [comment]
This story was completed by me, @Dinferno-lol, and @Ghaith-Chrit 
[registration.webm](https://github.com/JamesPartsafas/ConcordiaCurriculumManager/assets/56362880/7d0ec727-b866-4c29-92d9-fa54ca073d16)

**Comment by Dinferno-lol** [comment]
https://github.com/JamesPartsafas/ConcordiaCurriculumManager/assets/77465567/5590ffba-14b8-4b99-8a94-cbb9f1ac3f1f
