### ISSUE TITLE
Home page

### ISSUE THREAD

**Issue by kennyphan100** [JamesPartsafas/ConcordiaCurriculumManager#9]
As a faculty member, I want to access a home page, so I can view and use the functionalities provided by the website.

[Story Points: 2]
[Priority: High]
[Risk: Low]

Tasks:
- [x] #54 
- [x] #110  

Demo steps:
Given I’m a logged-in or logged-out system user
When I land on the website’s home page
Then the system displays the home page

**Comment by Dinferno-lol** [comment]
https://github.com/JamesPartsafas/ConcordiaCurriculumManager/assets/77465567/5616c695-e067-4346-a0e8-4243f0390912
